[package]
name = "alaya-bridge"
version.workspace = true
edition.workspace = true

[lib]
name = "alaya_bridge"
path = "src/lib.rs"

[[bin]]
name = "alaya-bridge"
path = "src/main.rs"

[dev-dependencies]
anyhow = "1"

[dependencies]
alaya-types = { path = "../alaya-types" }
tokio = { workspace = true }
axum = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
