//! ops-console — OIDC-gated web console for the 27b workspace (LAB-1684).
//!
//! Two-tenant skeleton (LAB-1641 constraint A): the Ālaya memory-curation
//! module ships here; the anthropic-lb read-only pane lands as a second route
//! module (LAB-1964). Trust model (D2, ratified 2026-08-15): the browser
//! authenticates with an OIDC session; every alaya-server call happens
//! server-side with the static bearer. No credential reaches the browser.
//!
//! Session posture (LAB-1694 panel, pass/fail set): CSRF token + Origin check
//! on every POST, `HttpOnly`/`SameSite`/`Secure` cookies, session regeneration
//! on the OIDC callback, pinned `redirect_uri`, fail-closed configuration.

mod alaya;
mod config;
mod error;
mod oidc;
mod routes;
mod session;
mod state;
mod ui;

use axum::Router;
use axum::extract::{FromRef, Request, State};
use axum::http::{HeaderValue, Method, StatusCode, header};
use axum::middleware::{self, Next};
use axum::response::{IntoResponse, Response};
use axum::routing::{get, post};

use crate::state::AppState;

/// Generated by Tailwind CSS v4 from the vendored Rust/UI class strings —
/// see `style/input.css` + `scripts/build-css.sh` in this crate.
const CONSOLE_CSS: &str = include_str!("../static/console.css");

async fn healthz() -> &'static str {
    "ok"
}

async fn console_css() -> impl IntoResponse {
    (
        [
            (header::CONTENT_TYPE, "text/css; charset=utf-8"),
            (header::CACHE_CONTROL, "public, max-age=3600"),
        ],
        CONSOLE_CSS,
    )
}

/// Strict same-origin gate for every state-changing request: the Origin
/// header must be present and equal the configured public origin. Forms we
/// serve always satisfy this; a cross-site POST never can.
async fn origin_check(State(state): State<AppState>, req: Request, next: Next) -> Response {
    if req.method() != Method::GET && req.method() != Method::HEAD {
        let expected = state.config.public_origin();
        let ok = req
            .headers()
            .get(header::ORIGIN)
            .and_then(|o| o.to_str().ok())
            .map(|o| o == expected)
            .unwrap_or(false);
        if !ok {
            return (StatusCode::FORBIDDEN, "cross-origin request rejected").into_response();
        }
    }
    next.run(req).await
}

/// Sliding idle-timeout refresh (team session rule: idle ≤ 15 min): every
/// request carrying a valid session gets a re-issued cookie with a fresh
/// `last_seen`. Skipped when the handler already set the session cookie
/// itself (login callback, logout) — a stale refresh must never clobber a
/// deliberate mint or removal.
async fn session_refresh(State(state): State<AppState>, req: Request, next: Next) -> Response {
    use axum_extra::extract::cookie::{Key, PrivateCookieJar};
    let key = Key::from_ref(&state);
    let jar = PrivateCookieJar::from_headers(req.headers(), key);
    let refreshed = session::read_session(&jar).map(|mut s| {
        s.last_seen = session::now_epoch();
        s
    });

    let resp = next.run(req).await;

    let Some(sess) = refreshed else { return resp };
    let handler_touched_session = resp
        .headers()
        .get_all(header::SET_COOKIE)
        .iter()
        .filter_map(|v| v.to_str().ok())
        .any(|v| v.starts_with(session::SESSION_COOKIE));
    if handler_touched_session {
        return resp;
    }
    let jar = session::session_cookie(jar, &sess, state.secure_cookies());
    (jar, resp).into_response()
}

/// No inline JS exists, so the CSP can be maximally strict.
async fn security_headers(req: Request, next: Next) -> Response {
    let mut resp = next.run(req).await;
    let h = resp.headers_mut();
    h.insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(
            "default-src 'none'; style-src 'self'; img-src 'self'; base-uri 'none'; \
             form-action 'self'; frame-ancestors 'none'",
        ),
    );
    h.insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    h.insert(header::X_FRAME_OPTIONS, HeaderValue::from_static("DENY"));
    h.insert(
        header::REFERRER_POLICY,
        HeaderValue::from_static("same-origin"),
    );
    resp
}

fn app(state: AppState) -> Router {
    // Session enforcement lives in the `Session` extractor: every handler
    // below except healthz/css/login/callback requires it, so an unlisted
    // future route without the extractor serves nothing sensitive by itself.
    Router::new()
        .route("/healthz", get(healthz))
        .route("/static/console.css", get(console_css))
        .route("/auth/login", get(routes::auth::login))
        .route("/auth/callback", get(routes::auth::callback))
        .route("/auth/logout", post(routes::auth::logout))
        .route("/", get(routes::home::home))
        .route("/alaya", get(routes::alaya::browse))
        .route("/alaya/memory/{hash}", get(routes::alaya::detail))
        .route(
            "/alaya/memory/{hash}/delete",
            post(routes::alaya::delete_memory),
        )
        .route(
            "/alaya/memory/{hash}/correct",
            post(routes::alaya::correct_and_supersede),
        )
        .route(
            "/alaya/supersede",
            get(routes::alaya::supersede_form).post(routes::alaya::supersede_submit),
        )
        .route(
            "/alaya/relation/create",
            post(routes::alaya::relation_create),
        )
        .route(
            "/alaya/relation/delete",
            post(routes::alaya::relation_delete),
        )
        .route("/alaya/duplicates", get(routes::alaya::duplicates))
        .route("/alaya/duplicates/merge", post(routes::alaya::merge_submit))
        .route("/alaya/contradictions", get(routes::alaya::contradictions))
        .route("/alaya/auth", get(routes::alaya::auth_view))
        .layer(middleware::from_fn_with_state(state.clone(), origin_check))
        .layer(middleware::from_fn_with_state(
            state.clone(),
            session_refresh,
        ))
        .layer(middleware::from_fn(security_headers))
        .layer(tower_http::trace::TraceLayer::new_for_http())
        .with_state(state)
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "ops_console=info,tower_http=info".into()),
        )
        .init();

    // Fail-closed: any missing/invalid config value refuses startup (AC10).
    let config = match config::Config::from_env() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("ops-console refusing to start: {e}");
            std::process::exit(1);
        }
    };
    tracing::info!(?config, "ops-console starting");

    let listen = config.listen_addr.clone();
    let state = AppState::new(config);
    let listener = tokio::net::TcpListener::bind(&listen)
        .await
        .expect("failed to bind");
    tracing::info!("ops-console listening on {listen}");

    axum::serve(listener, app(state))
        .with_graceful_shutdown(shutdown_signal())
        .await
        .expect("server error");
}

async fn shutdown_signal() {
    let ctrl_c = tokio::signal::ctrl_c();
    let mut sigterm = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
        .expect("failed to register SIGTERM handler");
    tokio::select! {
        _ = ctrl_c => tracing::info!("received SIGINT, shutting down…"),
        _ = sigterm.recv() => tracing::info!("received SIGTERM, shutting down…"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::Request as HttpRequest;
    use http_body_util::BodyExt;
    use tower::ServiceExt;

    const TEST_SECRET: &[u8] = b"0123456789abcdef0123456789abcdef-test";

    fn test_state() -> AppState {
        let config = config::Config {
            listen_addr: "127.0.0.1:0".into(),
            public_url: "https://console.test".parse().unwrap(),
            oidc_issuer: "https://id.test".into(),
            oidc_client_id: "console".into(),
            oidc_client_secret: "oidc-client-secret-value".into(),
            allowed_subjects: vec!["admin-sub".into()],
            session_secret: TEST_SECRET.to_vec(),
            // Closed port: upstream calls fail fast; pages must degrade, not leak.
            alaya_url: "http://127.0.0.1:1".parse().unwrap(),
            alaya_api_key: "alaya-bearer-secret-value".into(),
        };
        AppState::new(config)
    }

    /// Mint a valid encrypted session cookie the way the server would —
    /// the key derivation must match `AppState::new` exactly.
    fn session_cookie_header(state: &AppState, sess: &session::Session) -> String {
        use sha2::Digest;
        let expanded = sha2::Sha512::digest(&state.config.session_secret);
        let key = cookie::Key::from(&expanded);
        let mut jar = cookie::CookieJar::new();
        jar.private_mut(&key).add(cookie::Cookie::new(
            session::SESSION_COOKIE,
            serde_json::to_string(sess).unwrap(),
        ));
        let c = jar.get(session::SESSION_COOKIE).unwrap();
        format!("{}={}", c.name(), c.value())
    }

    async fn body_string(resp: Response) -> String {
        let bytes = resp.into_body().collect().await.unwrap().to_bytes();
        String::from_utf8_lossy(&bytes).to_string()
    }

    #[tokio::test]
    async fn healthz_is_open_and_css_is_served() {
        let app = app(test_state());
        let resp = app
            .clone()
            .oneshot(HttpRequest::get("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);

        let resp = app
            .oneshot(
                HttpRequest::get("/static/console.css")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
    }

    #[tokio::test]
    async fn unauthenticated_get_redirects_to_login() {
        let app = app(test_state());
        let resp = app
            .oneshot(HttpRequest::get("/alaya").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        assert_eq!(resp.headers().get(header::LOCATION).unwrap(), "/auth/login");
    }

    #[tokio::test]
    async fn post_without_origin_is_rejected() {
        let app = app(test_state());
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/supersede")
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from("csrf=x&old_hash=a&new_hash=b"))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn post_with_wrong_origin_is_rejected() {
        let app = app(test_state());
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/supersede")
                    .header(header::ORIGIN, "https://evil.test")
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from("csrf=x&old_hash=a&new_hash=b"))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn post_with_bad_csrf_is_rejected_even_with_session() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let old = "a".repeat(64);
        let new = "b".repeat(64);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/supersede")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie_header)
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(format!(
                        "csrf=WRONG&old_hash={old}&new_hash={new}&reason=r"
                    )))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn post_without_session_is_403_not_redirect() {
        let app = app(test_state());
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/relation/create")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from("csrf=x"))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    /// AC8: no server-held credential may ever appear in a rendered page —
    /// including on the home page, whose upstream call fails here.
    #[tokio::test]
    async fn rendered_pages_never_contain_credentials() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let html = body_string(resp).await;
        assert!(!html.contains("alaya-bearer-secret-value"));
        assert!(!html.contains("oidc-client-secret-value"));
    }

    #[tokio::test]
    async fn expired_session_redirects_to_login() {
        let state = test_state();
        let mut sess = session::new_session("admin-sub".into(), None, None);
        sess.exp = session::now_epoch() - 10;
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/alaya")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
    }

    /// Sliding idle timeout: an authenticated GET re-issues the session
    /// cookie with a fresh last_seen.
    #[tokio::test]
    async fn authenticated_request_refreshes_session_cookie() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let refreshed = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .filter_map(|v| v.to_str().ok())
            .any(|v| v.starts_with(session::SESSION_COOKIE) && !v.contains("Max-Age=0"));
        assert!(refreshed, "session cookie must slide on activity");
    }

    /// The refresh middleware must never clobber logout's removal cookie:
    /// exactly one console_session Set-Cookie, and it's the removal.
    #[tokio::test]
    async fn logout_removal_is_not_clobbered_by_refresh() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let csrf = sess.csrf.clone();
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::post("/auth/logout")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie_header)
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(format!("csrf={csrf}")))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        let session_cookies: Vec<&str> = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .filter_map(|v| v.to_str().ok())
            .filter(|v| v.starts_with(session::SESSION_COOKIE))
            .collect();
        assert_eq!(session_cookies.len(), 1, "exactly one session Set-Cookie");
        assert!(
            session_cookies[0].contains("Max-Age=0"),
            "the surviving session cookie must be the removal: {}",
            session_cookies[0]
        );
    }

    /// Idle-expired session (inside absolute lifetime) is rejected.
    #[tokio::test]
    async fn idle_expired_session_redirects_to_login() {
        let state = test_state();
        let mut sess = session::new_session("admin-sub".into(), None, None);
        sess.last_seen = session::now_epoch() - session::IDLE_TTL_SECS - 1;
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/alaya")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
    }

    #[tokio::test]
    async fn security_headers_are_set() {
        let app = app(test_state());
        let resp = app
            .oneshot(HttpRequest::get("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap();
        let csp = resp
            .headers()
            .get(header::CONTENT_SECURITY_POLICY)
            .unwrap()
            .to_str()
            .unwrap();
        assert!(csp.contains("default-src 'none'"));
        assert_eq!(resp.headers().get(header::X_FRAME_OPTIONS).unwrap(), "DENY");
    }

    /// Malformed hash in the path is rejected before any upstream call.
    #[tokio::test]
    async fn invalid_hash_is_bad_request() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/alaya/memory/not-a-hash")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
    }
}
