//! ops-console — OIDC-gated web console for the 27b workspace (LAB-1684).
//!
//! Two-tenant console (LAB-1641 constraint A): the Ālaya memory-curation
//! module and the anthropic-lb read-only monitoring pane as a second route
//! module. Trust model (D2, ratified 2026-08-15): the browser
//! authenticates with an OIDC session; every upstream call (alaya-server
//! bearer, anthropic-lb operator key) happens server-side. No credential
//! reaches the browser.
//!
//! Session posture (LAB-1694 panel, pass/fail set): CSRF token + Origin check
//! on every POST, `HttpOnly`/`SameSite`/`Secure` cookies, session regeneration
//! on the OIDC callback, pinned `redirect_uri`, fail-closed configuration.

mod alaya;
mod config;
mod error;
mod http;
mod lb;
mod oidc;
mod routes;
mod session;
mod state;
#[cfg(test)]
mod testkit;
#[cfg(test)]
mod testlog;
mod ui;

use axum::Router;
use axum::extract::{FromRef, Request, State};
use axum::http::{HeaderValue, Method, StatusCode, header};
use axum::middleware::{self, Next};
use axum::response::{IntoResponse, Response};
use axum::routing::{get, post};

use crate::state::AppState;

/// Generated by Tailwind CSS v4 from the vendored Rust/UI class strings —
/// see `style/input.css` + `scripts/build-css.sh` in this crate.
const CONSOLE_CSS: &str = include_str!("../static/console.css");

async fn healthz() -> &'static str {
    "ok"
}

async fn console_css() -> impl IntoResponse {
    (
        [
            (header::CONTENT_TYPE, "text/css; charset=utf-8"),
            (header::CACHE_CONTROL, "public, max-age=3600"),
        ],
        CONSOLE_CSS,
    )
}

/// Strict same-origin gate for every state-changing request: the Origin
/// header must be present and equal the configured public origin. Forms we
/// serve always satisfy this; a cross-site POST never can.
async fn origin_check(State(state): State<AppState>, req: Request, next: Next) -> Response {
    if req.method() != Method::GET && req.method() != Method::HEAD {
        let expected = state.config.public_origin();
        let ok = req
            .headers()
            .get(header::ORIGIN)
            .and_then(|o| o.to_str().ok())
            .map(|o| o == expected)
            .unwrap_or(false);
        if !ok {
            return (StatusCode::FORBIDDEN, "cross-origin request rejected").into_response();
        }
    }
    next.run(req).await
}

/// Sliding idle-timeout refresh (team session rule: idle ≤ 15 min): every
/// request carrying a valid session gets a re-issued cookie with a fresh
/// `last_seen`. Skipped when the handler already set the session cookie
/// itself (login callback, logout) — a stale refresh must never clobber a
/// deliberate mint or removal.
async fn session_refresh(State(state): State<AppState>, req: Request, next: Next) -> Response {
    use axum_extra::extract::cookie::{Key, PrivateCookieJar};
    let key = Key::from_ref(&state);
    let jar = PrivateCookieJar::from_headers(req.headers(), key);
    // A logged-out sid must never be re-issued (CWE-613).
    let refreshed = session::read_session(&jar)
        .filter(|s| !state.is_revoked(&s.sid))
        .map(|mut s| {
            s.last_seen = session::now_epoch();
            s
        });

    let resp = next.run(req).await;

    let Some(sess) = refreshed else { return resp };
    let handler_touched_session = resp
        .headers()
        .get_all(header::SET_COOKIE)
        .iter()
        .filter_map(|v| v.to_str().ok())
        .any(|v| v.starts_with(session::SESSION_COOKIE));
    if handler_touched_session {
        return resp;
    }
    let jar = session::session_cookie(jar, &sess, state.secure_cookies());
    (jar, resp).into_response()
}

/// No inline JS exists, so the CSP can be maximally strict.
async fn security_headers(req: Request, next: Next) -> Response {
    let mut resp = next.run(req).await;
    let h = resp.headers_mut();
    h.insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(
            "default-src 'none'; style-src 'self'; img-src 'self'; base-uri 'none'; \
             form-action 'self'; frame-ancestors 'none'",
        ),
    );
    h.insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    h.insert(header::X_FRAME_OPTIONS, HeaderValue::from_static("DENY"));
    h.insert(
        header::REFERRER_POLICY,
        HeaderValue::from_static("same-origin"),
    );
    resp
}

fn app(state: AppState) -> Router {
    // Session enforcement lives in the `Session` extractor: every handler
    // below except healthz/css/login/callback requires it, so an unlisted
    // future route without the extractor serves nothing sensitive by itself.
    Router::new()
        .route("/healthz", get(healthz))
        .route("/static/console.css", get(console_css))
        .route("/auth/login", get(routes::auth::login))
        .route("/auth/callback", get(routes::auth::callback))
        .route("/auth/logout", post(routes::auth::logout))
        .route("/", get(routes::home::home))
        .route("/alaya", get(routes::alaya::browse))
        .route("/alaya/memory/{hash}", get(routes::alaya::detail))
        .route(
            "/alaya/memory/{hash}/delete",
            post(routes::alaya::delete_memory),
        )
        .route(
            "/alaya/memory/{hash}/correct",
            post(routes::alaya::correct_and_supersede),
        )
        .route(
            "/alaya/supersede",
            get(routes::alaya::supersede_form).post(routes::alaya::supersede_submit),
        )
        .route(
            "/alaya/relation/create",
            post(routes::alaya::relation_create),
        )
        .route(
            "/alaya/relation/delete",
            post(routes::alaya::relation_delete),
        )
        .route("/alaya/duplicates", get(routes::alaya::duplicates))
        .route("/alaya/duplicates/merge", post(routes::alaya::merge_submit))
        .route("/alaya/contradictions", get(routes::alaya::contradictions))
        .route("/alaya/contradictions/pair", get(routes::alaya::pair_page))
        .route(
            "/alaya/contradictions/keep-both",
            post(routes::alaya::keep_both_submit),
        )
        .route(
            "/alaya/contradictions/keep-both/bulk",
            post(routes::alaya::keep_both_bulk),
        )
        .route(
            "/alaya/contradictions/reopen",
            post(routes::alaya::reopen_submit),
        )
        .route("/alaya/auth", get(routes::alaya::auth_view))
        // anthropic-lb module: GET only, by design. No POST route to the LB
        // exists and none may be added here.
        .route("/lb", get(routes::lb::pane))
        .layer(middleware::from_fn_with_state(state.clone(), origin_check))
        .layer(middleware::from_fn_with_state(
            state.clone(),
            session_refresh,
        ))
        .layer(middleware::from_fn(security_headers))
        // The request span records the path, not the full URI: a query
        // string is never a safe thing to log.
        .layer(
            tower_http::trace::TraceLayer::new_for_http().make_span_with(|req: &Request| {
                tracing::debug_span!(
                    "request",
                    method = %req.method(),
                    path = %req.uri().path(),
                )
            }),
        )
        .with_state(state)
}

/// The binary's log subscriber, taking the filter and writer so a test can
/// drive this exact one without depending on the ambient `RUST_LOG`. JSON, one
/// object per record: the structured fields (`sub`, `issuer`, `cause`, ...)
/// are what an outage is triaged off, and the encoder escapes every C0
/// control char in every field however a call site records it — `%`
/// included. It does not escape U+2028/U+2029/NEL, so recording untrusted
/// values with `?` and a length cap still matters.
fn log_subscriber<W>(
    filter: tracing_subscriber::EnvFilter,
    writer: W,
) -> impl tracing::Subscriber + Send + Sync + 'static
where
    W: for<'a> tracing_subscriber::fmt::MakeWriter<'a> + Send + Sync + 'static,
{
    tracing_subscriber::fmt()
        .json()
        .with_env_filter(filter)
        .with_writer(writer)
        .finish()
}

#[tokio::main]
async fn main() {
    use tracing_subscriber::util::SubscriberInitExt;
    let filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| "ops_console=info,tower_http=info".into());
    log_subscriber(filter, std::io::stdout).init();

    // Fail-closed: any missing/invalid config value refuses startup (AC10).
    let config = match config::Config::from_env() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("ops-console refusing to start: {e}");
            std::process::exit(1);
        }
    };
    tracing::info!(?config, "ops-console starting");

    let listen = config.listen_addr.clone();
    let state = AppState::new(config);
    let listener = tokio::net::TcpListener::bind(&listen)
        .await
        .expect("failed to bind");
    tracing::info!("ops-console listening on {listen}");

    axum::serve(listener, app(state))
        .with_graceful_shutdown(shutdown_signal())
        .await
        .expect("server error");
}

async fn shutdown_signal() {
    let ctrl_c = tokio::signal::ctrl_c();
    let mut sigterm = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
        .expect("failed to register SIGTERM handler");
    tokio::select! {
        _ = ctrl_c => tracing::info!("received SIGINT, shutting down…"),
        _ = sigterm.recv() => tracing::info!("received SIGTERM, shutting down…"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::Request as HttpRequest;
    use http_body_util::BodyExt;
    use tower::ServiceExt;

    const TEST_SECRET: &[u8] = b"0123456789abcdef0123456789abcdef-test";
    const LB_KEY: &str = "lb-operator-key-secret-value";

    fn test_config() -> config::Config {
        config::Config {
            listen_addr: "127.0.0.1:0".into(),
            public_url: "https://console.test".parse().unwrap(),
            oidc_issuer: "https://id.test".into(),
            oidc_client_id: "console".into(),
            oidc_client_secret: "oidc-client-secret-value".into(),
            allowed_subjects: vec!["admin-sub".into()],
            session_secret: TEST_SECRET.to_vec(),
            // Closed port: upstream calls fail fast; pages must degrade, not leak.
            alaya_url: "http://127.0.0.1:1".parse().unwrap(),
            alaya_api_key: "alaya-bearer-secret-value".into(),
            lb: None,
        }
    }

    fn test_state() -> AppState {
        AppState::new(test_config())
    }

    /// LB module configured against closed ports: both upstreams fail fast.
    fn test_state_with_lb() -> AppState {
        let mut config = test_config();
        config.lb = Some(config::LbConfig {
            url: "http://127.0.0.1:1".parse().unwrap(),
            api_key: LB_KEY.into(),
            metrics_url: "http://127.0.0.1:1".parse().unwrap(),
        });
        AppState::new(config)
    }

    /// Mint a valid encrypted cookie the way the server would — the key
    /// derivation must match `AppState::new` exactly.
    fn encrypted_cookie_header(state: &AppState, name: &'static str, value: String) -> String {
        use sha2::Digest;
        let expanded = sha2::Sha512::digest(&state.config.session_secret);
        let key = cookie::Key::from(&expanded);
        let mut jar = cookie::CookieJar::new();
        jar.private_mut(&key).add(cookie::Cookie::new(name, value));
        let c = jar.get(name).unwrap();
        format!("{}={}", c.name(), c.value())
    }

    fn session_cookie_header(state: &AppState, sess: &session::Session) -> String {
        encrypted_cookie_header(
            state,
            session::SESSION_COOKIE,
            serde_json::to_string(sess).unwrap(),
        )
    }

    fn login_cookie_header(state: &AppState, login: &session::LoginState) -> String {
        encrypted_cookie_header(
            state,
            session::LOGIN_COOKIE,
            serde_json::to_string(login).unwrap(),
        )
    }

    async fn body_string(resp: Response) -> String {
        let bytes = resp.into_body().collect().await.unwrap().to_bytes();
        String::from_utf8_lossy(&bytes).to_string()
    }

    #[tokio::test]
    async fn healthz_is_open_and_css_is_served() {
        let app = app(test_state());
        let resp = app
            .clone()
            .oneshot(HttpRequest::get("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);

        let resp = app
            .oneshot(
                HttpRequest::get("/static/console.css")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
    }

    #[tokio::test]
    async fn unauthenticated_get_redirects_to_login() {
        let app = app(test_state());
        let resp = app
            .oneshot(HttpRequest::get("/alaya").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        assert_eq!(resp.headers().get(header::LOCATION).unwrap(), "/auth/login");
    }

    #[tokio::test]
    async fn post_without_origin_is_rejected() {
        let app = app(test_state());
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/supersede")
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from("csrf=x&old_hash=a&new_hash=b"))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn post_with_wrong_origin_is_rejected() {
        let app = app(test_state());
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/supersede")
                    .header(header::ORIGIN, "https://evil.test")
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from("csrf=x&old_hash=a&new_hash=b"))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn keep_both_post_rejects_a_bad_csrf_before_any_upstream_call() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let a = "a".repeat(64);
        let b = "b".repeat(64);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/contradictions/keep-both")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie_header)
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(format!(
                        "csrf=WRONG&memory_a_hash={a}&memory_b_hash={b}"
                    )))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn post_with_bad_csrf_is_rejected_even_with_session() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let old = "a".repeat(64);
        let new = "b".repeat(64);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/supersede")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie_header)
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(format!(
                        "csrf=WRONG&old_hash={old}&new_hash={new}&reason=r"
                    )))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    #[tokio::test]
    async fn post_without_session_is_403_not_redirect() {
        let app = app(test_state());
        let resp = app
            .oneshot(
                HttpRequest::post("/alaya/relation/create")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from("csrf=x"))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }

    /// AC8: no server-held credential may ever appear in a rendered page —
    /// including on the home page and the LB pane, whose upstream calls all
    /// fail here (every error path renders).
    #[tokio::test]
    async fn rendered_pages_never_contain_credentials() {
        let state = test_state_with_lb();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        for path in ["/", "/lb"] {
            let resp = app
                .clone()
                .oneshot(
                    HttpRequest::get(path)
                        .header(header::COOKIE, cookie_header.clone())
                        .body(Body::empty())
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(resp.status(), StatusCode::OK, "{path}");
            let html = body_string(resp).await;
            assert!(!html.contains("alaya-bearer-secret-value"), "{path}");
            assert!(!html.contains("oidc-client-secret-value"), "{path}");
            assert!(!html.contains(LB_KEY), "{path}");
        }
    }

    #[tokio::test]
    async fn lb_pane_requires_a_session() {
        let app = app(test_state_with_lb());
        let resp = app
            .oneshot(HttpRequest::get("/lb").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        assert_eq!(resp.headers().get(header::LOCATION).unwrap(), "/auth/login");
    }

    /// Module disabled (no LB_* env): the pane and the home card say so
    /// explicitly rather than 404ing or rendering an empty table.
    #[tokio::test]
    async fn lb_pane_reports_an_unconfigured_module() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        for path in ["/lb", "/"] {
            let resp = app
                .clone()
                .oneshot(
                    HttpRequest::get(path)
                        .header(header::COOKIE, cookie_header.clone())
                        .body(Body::empty())
                        .unwrap(),
                )
                .await
                .unwrap();
            assert_eq!(resp.status(), StatusCode::OK, "{path}");
            assert!(body_string(resp).await.contains("not configured"), "{path}");
        }
    }

    /// Each section degrades on its own: with both upstreams dark the page
    /// still renders, names each unavailable source, keeps the provenance
    /// text, and carries no form that could POST to the LB.
    #[tokio::test]
    async fn lb_pane_degrades_per_section_and_has_no_write_path() {
        let state = test_state_with_lb();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/lb")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let html = body_string(resp).await;
        assert!(html.contains("anthropic-lb: connection failed"), "{html}");
        assert!(html.contains("metrics: connection failed"), "{html}");
        assert!(html.contains("TOML, GitOps"));
        // The only form on any authenticated page is the logout form.
        assert_eq!(html.matches("<form").count(), 1);
        assert!(html.contains("action=\"/auth/logout\""));
    }

    #[tokio::test]
    async fn expired_session_redirects_to_login() {
        let state = test_state();
        let mut sess = session::new_session("admin-sub".into(), None, None);
        sess.exp = session::now_epoch() - 10;
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/alaya")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
    }

    /// Sliding idle timeout: an authenticated GET re-issues the session
    /// cookie with a fresh last_seen.
    #[tokio::test]
    async fn authenticated_request_refreshes_session_cookie() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let refreshed = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .filter_map(|v| v.to_str().ok())
            .any(|v| v.starts_with(session::SESSION_COOKIE) && !v.contains("Max-Age=0"));
        assert!(refreshed, "session cookie must slide on activity");
    }

    /// The refresh middleware must never clobber logout's removal cookie:
    /// exactly one console_session Set-Cookie, and it's the removal.
    #[tokio::test]
    async fn logout_removal_is_not_clobbered_by_refresh() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let csrf = sess.csrf.clone();
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::post("/auth/logout")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie_header)
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(format!("csrf={csrf}")))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        let session_cookies: Vec<&str> = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .filter_map(|v| v.to_str().ok())
            .filter(|v| v.starts_with(session::SESSION_COOKIE))
            .collect();
        assert_eq!(session_cookies.len(), 1, "exactly one session Set-Cookie");
        assert!(
            session_cookies[0].contains("Max-Age=0"),
            "the surviving session cookie must be the removal: {}",
            session_cookies[0]
        );
    }

    /// CWE-613: after logout, the old cookie is server-side revoked — a
    /// request replaying it (e.g. an in-flight refresh racing the logout)
    /// must be rejected AND must not re-issue the session cookie.
    #[tokio::test]
    async fn logged_out_cookie_is_revoked_and_never_reissued() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let csrf = sess.csrf.clone();
        let app = app(state);

        let resp = app
            .clone()
            .oneshot(
                HttpRequest::post("/auth/logout")
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie_header.clone())
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(format!("csrf={csrf}")))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);

        // Replay the original (still cryptographically valid) cookie.
        let resp = app
            .oneshot(
                HttpRequest::get("/alaya")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(
            resp.status(),
            StatusCode::SEE_OTHER,
            "revoked sid must not authenticate"
        );
        let reissued = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .filter_map(|v| v.to_str().ok())
            .any(|v| v.starts_with(session::SESSION_COOKIE) && !v.contains("Max-Age=0"));
        assert!(
            !reissued,
            "a revoked session must never be re-issued by the refresh middleware"
        );
    }

    /// Idle-expired session (inside absolute lifetime) is rejected.
    #[tokio::test]
    async fn idle_expired_session_redirects_to_login() {
        let state = test_state();
        let mut sess = session::new_session("admin-sub".into(), None, None);
        sess.last_seen = session::now_epoch() - session::IDLE_TTL_SECS - 1;
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/alaya")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
    }

    #[tokio::test]
    async fn security_headers_are_set() {
        let app = app(test_state());
        let resp = app
            .oneshot(HttpRequest::get("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap();
        let csp = resp
            .headers()
            .get(header::CONTENT_SECURITY_POLICY)
            .unwrap()
            .to_str()
            .unwrap();
        assert!(csp.contains("default-src 'none'"));
        assert_eq!(resp.headers().get(header::X_FRAME_OPTIONS).unwrap(), "DENY");
    }

    /// Malformed hash in the path is rejected before any upstream call.
    #[tokio::test]
    async fn invalid_hash_is_bad_request() {
        let state = test_state();
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let app = app(state);
        let resp = app
            .oneshot(
                HttpRequest::get("/alaya/memory/not-a-hash")
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
    }

    /// Serve `routes` on a loopback ephemeral port and return its origin.
    /// `ALAYA_URL` is plaintext pod-to-pod, so a compromised or on-path
    /// alaya-server is the threat model this stands in for.
    async fn fake_upstream(routes: Router) -> String {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        // `let _`, not `unwrap`: there is no error value to surface.
        // `axum::serve` is typed `io::Result<()>` but documents that it
        // never completes or returns an error — accept errors are retried
        // inside its own loop. Nothing here holds the handle, so the task
        // ends with the test's runtime. The one observable failure is the
        // bind, and that is the `unwrap()` above, outside the spawn, where
        // it panics the test rather than hanging it.
        tokio::spawn(async move {
            let _ = axum::serve(listener, routes).await;
        });
        format!("http://{addr}")
    }

    /// The correction's `content_hash` is alaya-server's answer echoed
    /// verbatim, and it reaches a log field, `memory_href` and `supersede`.
    /// Unvalidated it forges pod-log records — in the audit trail for this
    /// very write — so it must be refused before any of them, and the
    /// refusal must still say that the store half committed.
    #[tokio::test]
    async fn a_malformed_store_content_hash_is_refused_and_never_reaches_the_log_raw() {
        use std::sync::Arc;
        use std::sync::atomic::{AtomicUsize, Ordering};

        const FORGED: &str = "aaaa\n2026-09-22T12:00:00Z  INFO ops_console: corrected + superseded sub=\"admin-sub\"";

        // Answers success, so the counter is the only thing that can notice a
        // supersede call. Without this route a regression that superseded onto
        // the forged hash and ignored the result got a 404, fell through to
        // the refusal, and passed every assertion below.
        let supersede_calls = Arc::new(AtomicUsize::new(0));
        let seen = supersede_calls.clone();
        let upstream = Router::new()
            .route(
                "/supersede",
                post(move || {
                    seen.fetch_add(1, Ordering::SeqCst);
                    async { axum::Json(serde_json::json!({ "success": true })) }
                }),
            )
            .route(
                "/memories/{hash}",
                get(|| async {
                    axum::Json(serde_json::json!({
                        "memory": { "memory_type": "note", "tags": [] }
                    }))
                }),
            )
            .route(
                "/store",
                post(|| async { axum::Json(serde_json::json!({ "content_hash": FORGED })) }),
            );
        let mut config = test_config();
        config.alaya_url = fake_upstream(upstream).await.parse().unwrap();

        let state = AppState::new(config);
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie_header = session_cookie_header(&state, &sess);
        let csrf = sess.csrf.clone();
        let hash = "a".repeat(64);
        let app = app(state);

        let buf = testlog::LogBuf::default();
        let resp = {
            let _capture = buf.capture();
            app.oneshot(
                HttpRequest::post(format!("/alaya/memory/{hash}/correct"))
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie_header)
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(format!("csrf={csrf}&content=fixed&reason=typo")))
                    .unwrap(),
            )
            .await
            .unwrap()
        };

        assert_eq!(resp.status(), StatusCode::BAD_GATEWAY);
        let body = body_string(resp).await;
        assert!(
            body.contains("WAS stored"),
            "the committed store half must not be hidden by the refusal: {body}"
        );
        assert_eq!(
            supersede_calls.load(Ordering::SeqCst),
            0,
            "a refused content_hash must never be sent upstream as a supersede target"
        );

        // Panics unless the refusal is in the pod log at all — it has to be
        // diagnosable.
        let record = buf.record("no usable content_hash");
        assert!(
            record.contains("\\n"),
            "the forged newline must reach the log escaped, never raw: {record}"
        );
        assert!(
            !record.contains("INFO ops_console: corrected + superseded"),
            "the forged record must be cut off before it completes: {record}"
        );
        // A cut at exactly 64 is a well-formed hash's own length, so an
        // unmarked one reads as a complete hash on a line that says there
        // was no usable hash.
        assert!(
            record.contains('…'),
            "a truncated answer must say it was truncated: {record}"
        );
        let leaked = testlog::separators_in(&record);
        assert!(
            leaked.is_empty(),
            "no upstream byte may reach the log raw: {leaked:?} in {record}"
        );
    }

    /// An IdP outage must log once, from the arm that saw it, and must not
    /// claim an id_token was rejected when none was received. The warning
    /// used to sit around a call whose first act is discovery — see
    /// `oidc::warn_rejected` for why that logged every outage twice.
    #[tokio::test]
    async fn an_idp_transport_failure_logs_once_and_claims_no_id_token_rejection() {
        let mut config = test_config();
        // Closed port: discovery fails before any token can exist.
        config.oidc_issuer = "http://127.0.0.1:1".into();
        let state = AppState::new(config);

        let login = session::new_login_state("/alaya".into());
        let cb_state = login.state.clone();
        let cookie_header = login_cookie_header(&state, &login);
        let app = app(state);

        let buf = testlog::LogBuf::default();
        let resp = {
            let _capture = buf.capture();
            app.oneshot(
                HttpRequest::get(format!("/auth/callback?code=xyz&state={cb_state}"))
                    .header(header::COOKIE, cookie_header)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap()
        };
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);

        let logged = buf.text();
        assert!(
            logged.contains("identity provider request failed"),
            "the outage must still be logged: {logged}"
        );
        assert!(
            !logged.contains("id_token rejected"),
            "no id_token was received, so none can have been rejected: {logged}"
        );
        // The defect this pins is the duplicate, not the wording: the arm
        // that saw the failure warns, and nothing above it warns again.
        //
        // Matched on the crate, not on `ops_console::oidc`: the warning this
        // guards against lived at the call site in `routes/auth.rs`, which
        // emits target `ops_console::routes::auth`, so a module-scoped
        // filter left the count at 1 and the duplicate half of this test
        // inert — the wording assertion above was carrying it alone.
        let console_warns = logged.lines().filter(|l| l.contains("ops_console")).count();
        assert_eq!(console_warns, 1, "one outage, one record: {logged}");
    }

    /// Asserted on the formatted log at `ops_console=debug` (the request span
    /// is built in `app`, so it takes this crate's target, not tower-http's)
    /// and `tower_http=debug` (tower-http's own request event), with positive
    /// controls so a broken capture fails instead of passing vacuously.
    #[tokio::test]
    async fn request_span_omits_query_string() {
        let sink = testlog::LogBuf::default();
        let resp = {
            let _capture = testlog::scoped(
                tracing_subscriber::fmt()
                    .with_env_filter("ops_console=debug,tower_http=debug")
                    .with_writer(sink.clone())
                    .with_ansi(false)
                    .finish(),
            );
            app(test_state())
                .oneshot(
                    HttpRequest::get("/auth/callback?code=CODE-SENTINEL&state=STATE-SENTINEL")
                        .body(Body::empty())
                        .unwrap(),
                )
                .await
                .unwrap()
        };
        // No login cookie: rejected before any identity-provider call.
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);

        let log = sink.text();
        assert!(
            log.contains("started processing request"),
            "positive control: the DEBUG request event must be captured:\n{log}"
        );
        assert!(
            log.contains("path=/auth/callback"),
            "positive control: the span must record the request path:\n{log}"
        );
        assert!(
            !log.contains("CODE-SENTINEL"),
            "authorization code reached the log:\n{log}"
        );
        assert!(
            !log.contains("STATE-SENTINEL"),
            "state parameter reached the log:\n{log}"
        );
    }

    /// Drives the binary's own subscriber, recording with `%` on purpose: the
    /// `?`-discipline tests (`oidc.rs`) prove call sites escape; this proves
    /// the encoder does even when a call site does not. The filter is pinned
    /// so an ambient `RUST_LOG` cannot drop the probe and fail the test for
    /// the wrong reason.
    #[test]
    fn json_log_keeps_a_display_recorded_newline_inside_one_record() {
        let hostile = "first\nforged record\r\u{1b}[2J";
        let sink = testlog::LogBuf::default();
        {
            let _capture = testlog::scoped(log_subscriber("warn".into(), sink.clone()));
            tracing::warn!(cause = %hostile, "json-injection-probe");
        }
        let logged = sink.text();
        assert_eq!(
            logged.lines().count(),
            1,
            "one event, one record: {logged:?}"
        );
        let record = sink.record("json-injection-probe");
        assert_eq!(
            testlog::separators_in(&record),
            Vec::<char>::new(),
            "{record:?}"
        );
        let json: serde_json::Value =
            serde_json::from_str(&record).expect("record is one JSON object");
        assert_eq!(
            json["fields"]["cause"], hostile,
            "value round-trips intact: {record}"
        );
    }

    /// `GET /auth/login` against `issuer`: the console built on it, plus the
    /// login cookie exactly as the client would send it back — the raw
    /// `name=value` from `Set-Cookie` — and the `state` from the redirect.
    async fn start_login(issuer: String) -> (Router, String, String) {
        let mut config = test_config();
        config.oidc_issuer = issuer;
        let app = app(AppState::new(config));
        let resp = app
            .clone()
            .oneshot(HttpRequest::get("/auth/login").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        let set_cookie = resp.headers()[header::SET_COOKIE].to_str().unwrap();
        let cookie = set_cookie.split(';').next().unwrap().to_string();
        assert!(cookie.starts_with(session::LOGIN_COOKIE), "{set_cookie}");
        let location: url::Url = resp.headers()[header::LOCATION]
            .to_str()
            .unwrap()
            .parse()
            .unwrap();
        let state = location
            .query_pairs()
            .find(|(k, _)| k == "state")
            .map(|(_, v)| v.into_owned())
            .expect("authorize redirect carries state");
        (app, cookie, state)
    }

    /// The raw header resent verbatim, the way a scripted caller replays it:
    /// never a jar that honours the callback's `Set-Cookie` deletion, which
    /// would pass against a deletion-only fix and prove nothing.
    fn callback_request(cookie: &str, state: &str) -> HttpRequest<Body> {
        HttpRequest::get(format!("/auth/callback?code=junk&state={state}"))
            .header(header::COOKIE, cookie)
            .body(Body::empty())
            .unwrap()
    }

    #[tokio::test]
    async fn a_replayed_login_state_never_reaches_the_token_endpoint() {
        use std::sync::atomic::Ordering;
        let (issuer, token_calls) = testkit::mock_idp().await;
        let (app, cookie, state) = start_login(issuer).await;

        let first = app
            .clone()
            .oneshot(callback_request(&cookie, &state))
            .await
            .unwrap();
        // Positive control: the first callback did reach the IdP, which
        // refused the junk code.
        assert_eq!(first.status(), StatusCode::FORBIDDEN);
        assert_eq!(token_calls.load(Ordering::SeqCst), 1);

        let replay = app
            .oneshot(callback_request(&cookie, &state))
            .await
            .unwrap();
        assert_eq!(
            token_calls.load(Ordering::SeqCst),
            1,
            "replay reached the IdP"
        );
        assert_eq!(replay.status(), StatusCode::BAD_REQUEST);
        assert!(body_string(replay).await.contains("already used"));
    }

    const CODE_SENTINEL: &str = "CODE-SENTINEL";
    const STATE_SENTINEL: &str = "STATE-SENTINEL";
    const NO_COOKIE_LINE: &str = "oidc: no valid login cookie — callback refused";

    /// Drive one callback under capture and pin its refusal: the status, one
    /// record naming it, and no sent credential anywhere in the log.
    async fn refused_callback(app: Router, req: HttpRequest<Body>) -> (StatusCode, String) {
        let buf = testlog::LogBuf::default();
        let status = {
            let _capture = buf.capture();
            app.oneshot(req).await.unwrap().status()
        };
        let logged = buf.text();
        for secret in [CODE_SENTINEL, STATE_SENTINEL] {
            assert!(
                !logged.contains(secret),
                "{secret} reached the log:\n{logged}"
            );
        }
        (status, logged)
    }

    fn assert_one_record(logged: &str, line: &str) {
        let n = logged.lines().filter(|l| l.contains(line)).count();
        assert_eq!(n, 1, "expected one {line:?} record:\n{logged}");
    }

    #[tokio::test]
    async fn a_callback_missing_its_state_is_logged_without_the_code() {
        let req = HttpRequest::get(format!("/auth/callback?code={CODE_SENTINEL}"))
            .body(Body::empty())
            .unwrap();
        let (status, logged) = refused_callback(app(test_state()), req).await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert_one_record(&logged, "oidc: missing code or state — callback refused");
    }

    #[tokio::test]
    async fn a_callback_with_no_login_cookie_is_logged_without_code_or_state() {
        let req = HttpRequest::get(format!(
            "/auth/callback?code={CODE_SENTINEL}&state={STATE_SENTINEL}"
        ))
        .body(Body::empty())
        .unwrap();
        let (status, logged) = refused_callback(app(test_state()), req).await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert_one_record(&logged, NO_COOKIE_LINE);
    }

    /// A genuine login cookie from `/auth/login`, answered with someone
    /// else's state: the login-CSRF shape. Neither state reaches the log,
    /// and the cookie arm it passed through stays silent.
    #[tokio::test]
    async fn a_state_mismatch_is_logged_without_either_state() {
        let (issuer, _token_calls) = testkit::mock_idp().await;
        let (app, cookie, real_state) = start_login(issuer).await;
        let req = HttpRequest::get(format!(
            "/auth/callback?code={CODE_SENTINEL}&state={STATE_SENTINEL}"
        ))
        .header(header::COOKIE, cookie)
        .body(Body::empty())
        .unwrap();
        let (status, logged) = refused_callback(app, req).await;
        assert_eq!(status, StatusCode::FORBIDDEN);
        assert_one_record(&logged, "oidc: login state mismatch — callback refused");
        assert!(
            !logged.contains(&real_state),
            "cookie state reached the log:\n{logged}"
        );
        assert!(
            !logged.contains(NO_COOKIE_LINE),
            "a valid cookie must not log the no-cookie refusal:\n{logged}"
        );
    }

    /// The first callback is parked on the token exchange when the second
    /// arrives, so this fails for any check made after the exchange rather
    /// than before it. One task on purpose: `join!` is what guarantees that
    /// ordering, where spawned tasks could run back to back. Atomicity of
    /// the test-and-set is the single lock guard in `consume_login`.
    #[tokio::test]
    async fn concurrent_callbacks_on_one_state_make_one_token_exchange() {
        use std::sync::atomic::Ordering;
        let (issuer, token_calls) = testkit::mock_idp().await;
        let (app, cookie, state) = start_login(issuer).await;

        let (a, b) = tokio::join!(
            app.clone().oneshot(callback_request(&cookie, &state)),
            app.clone().oneshot(callback_request(&cookie, &state)),
        );
        let mut statuses = [a.unwrap().status(), b.unwrap().status()];
        statuses.sort();
        assert_eq!(statuses, [StatusCode::BAD_REQUEST, StatusCode::FORBIDDEN]);
        assert_eq!(token_calls.load(Ordering::SeqCst), 1);
    }

    // ─── Contradictions triage ─────────────────────────────────────────────

    type Seen = std::sync::Arc<std::sync::Mutex<Vec<serde_json::Value>>>;

    /// A POST route that records every JSON body it receives and answers
    /// with `reply(body)`.
    fn recording<F>(seen: &Seen, reply: F) -> axum::routing::MethodRouter
    where
        F: Fn(&serde_json::Value) -> (StatusCode, serde_json::Value)
            + Clone
            + Send
            + Sync
            + 'static,
    {
        let seen = seen.clone();
        post(move |axum::Json(body): axum::Json<serde_json::Value>| {
            let (seen, reply) = (seen.clone(), reply.clone());
            async move {
                let (status, out) = reply(&body);
                seen.lock().unwrap().push(body);
                (status, axum::Json(out))
            }
        })
    }

    /// App state wired to `upstream`, plus a valid session cookie and its
    /// CSRF token.
    async fn triage_app(upstream: Router) -> (AppState, String, String) {
        let mut config = test_config();
        config.alaya_url = fake_upstream(upstream).await.parse().unwrap();
        let state = AppState::new(config);
        let sess = session::new_session("admin-sub".into(), None, None);
        let cookie = session_cookie_header(&state, &sess);
        (state, cookie, sess.csrf)
    }

    async fn get_page(state: &AppState, cookie: &str, uri: &str) -> (StatusCode, String) {
        let resp = app(state.clone())
            .oneshot(
                HttpRequest::get(uri)
                    .header(header::COOKIE, cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        (resp.status(), body_string(resp).await)
    }

    async fn post_form(state: &AppState, cookie: &str, uri: &str, form: String) -> Response {
        app(state.clone())
            .oneshot(
                HttpRequest::post(uri)
                    .header(header::ORIGIN, "https://console.test")
                    .header(header::COOKIE, cookie)
                    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
                    .body(Body::from(form))
                    .unwrap(),
            )
            .await
            .unwrap()
    }

    /// Decrypt the flash a handler set, the way the next GET would read it.
    /// axum-extra percent-encodes the value it writes but leaves `+` raw, so
    /// `+` is escaped first or form decoding would read it as a space.
    fn flash_of(state: &AppState, resp: &Response) -> session::Flash {
        use sha2::Digest;
        let key = cookie::Key::from(&sha2::Sha512::digest(&state.config.session_secret));
        let encoded = resp
            .headers()
            .get_all(header::SET_COOKIE)
            .iter()
            .filter_map(|v| cookie::Cookie::parse(v.to_str().ok()?.to_string()).ok())
            .find(|c| c.name() == session::FLASH_COOKIE)
            .expect("a flash cookie");
        let pair = format!("v={}", encoded.value().replace('+', "%2B"));
        let (_, value) = url::form_urlencoded::parse(pair.as_bytes()).next().unwrap();
        let mut jar = cookie::CookieJar::new();
        jar.add_original(cookie::Cookie::new(
            session::FLASH_COOKIE,
            value.into_owned(),
        ));
        let plain = jar
            .private(&key)
            .get(session::FLASH_COOKIE)
            .expect("decrypts");
        serde_json::from_str(plain.value()).unwrap()
    }

    fn location(resp: &Response) -> &str {
        resp.headers()
            .get(header::LOCATION)
            .unwrap()
            .to_str()
            .unwrap()
    }

    fn queue_pair(a: &str, b: &str) -> serde_json::Value {
        serde_json::json!({
            "memory_a_hash": a, "memory_b_hash": b, "confidence": 0.61,
            "created_at": 1788265604.0, "memory_a_content": "a summary",
            "memory_b_content": "b summary", "verdict": "supersession",
            "verdict_reason": "B is newer", "survivor": b, "verdict_confidence": 0.87,
            "verdict_model": "judge-model-x", "judged_at": 1788265700.0,
            "resolution": null, "resolved_at": null, "resolved_via": null,
        })
    }

    /// AC-1: the queue pages from the server's `next_offset`, carries the
    /// filters on both links, and offers Next only when the server said so.
    #[tokio::test]
    async fn queue_pages_from_next_offset_and_drops_next_without_it() {
        let seen = Seen::default();
        let upstream = Router::new().route(
            "/contradictions",
            recording(&seen, |body| {
                let next = (body["offset"] == 0).then_some(50);
                let pair = queue_pair(&"a".repeat(64), &"b".repeat(64));
                (
                    StatusCode::OK,
                    serde_json::json!({ "pairs": [pair], "next_offset": next }),
                )
            }),
        );
        let (state, cookie, _) = triage_app(upstream).await;

        let (status, first) =
            get_page(&state, &cookie, "/alaya/contradictions?verdict=coexist").await;
        assert_eq!(status, StatusCode::OK);
        assert!(
            first.contains("href=\"/alaya/contradictions?verdict=coexist&amp;offset=50\""),
            "{first}"
        );
        assert!(!first.contains("← Prev"));

        let (status, second) = get_page(
            &state,
            &cookie,
            "/alaya/contradictions?verdict=coexist&offset=50",
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        assert!(
            !second.contains("Next →"),
            "no next_offset, no Next: {second}"
        );
        assert!(
            second.contains("href=\"/alaya/contradictions?verdict=coexist\""),
            "Prev back to page 1"
        );
        assert!(second.contains("1 pairs from offset 50"));

        let bodies = seen.lock().unwrap().clone();
        assert_eq!(
            bodies[1],
            serde_json::json!({ "limit": 50, "offset": 50, "include_resolved": false, "verdicts": ["coexist"] })
        );
    }

    /// AC-2: the URL contract reaches the server unchanged; no `verdict`
    /// means the server default, and an unknown one never leaves the console.
    #[tokio::test]
    async fn queue_filters_reach_the_server_unchanged() {
        let seen = Seen::default();
        let upstream = Router::new().route(
            "/contradictions",
            recording(&seen, |_| {
                (StatusCode::OK, serde_json::json!({ "pairs": [] }))
            }),
        );
        let (state, cookie, _) = triage_app(upstream).await;

        let (status, _) = get_page(
            &state,
            &cookie,
            "/alaya/contradictions?verdict=unjudged&verdict=contradiction&resolved=1",
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        let (status, _) = get_page(&state, &cookie, "/alaya/contradictions").await;
        assert_eq!(status, StatusCode::OK);
        let (status, body) = get_page(&state, &cookie, "/alaya/contradictions?verdict=bogus").await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert!(body.contains("unknown verdict filter"));

        let bodies = seen.lock().unwrap().clone();
        assert_eq!(bodies.len(), 2, "the bad filter made no upstream call");
        assert_eq!(
            bodies[0],
            serde_json::json!({
                "limit": 50, "offset": 0, "include_resolved": true,
                "verdicts": ["unjudged", "contradiction"],
            })
        );
        assert_eq!(
            bodies[1],
            serde_json::json!({ "limit": 50, "offset": 0, "include_resolved": false })
        );
    }

    /// AC-4: both memories in full, the edge's verdict from the page it was
    /// opened from, and a failed fetch that says so in its own column.
    #[tokio::test]
    async fn pair_page_renders_both_memories_in_full_and_marks_a_failed_fetch() {
        let a = "a".repeat(64);
        let b = "b".repeat(64);
        let long = format!("{} END-OF-A", "x".repeat(400));
        let seen = Seen::default();
        let (pa, pb, long_c) = (a.clone(), b.clone(), long.clone());
        let upstream = Router::new()
            .route(
                "/contradictions",
                recording(&seen, move |_| {
                    (
                        StatusCode::OK,
                        serde_json::json!({ "pairs": [queue_pair(&pa, &pb)] }),
                    )
                }),
            )
            .route(
                "/memories/{hash}",
                get(move |axum::extract::Path(h): axum::extract::Path<String>| {
                    let long = long_c.clone();
                    async move {
                        if h.starts_with('a') {
                            (
                                StatusCode::OK,
                                axum::Json(serde_json::json!({ "found": true, "memory": {
                                    "content_hash": h, "content": long, "summary": "short a",
                                    "tags": ["tag-a"], "created_at": 1788265604.0,
                                    "metadata": { "superseded_by": "c".repeat(64) },
                                }})),
                            )
                        } else {
                            (
                                StatusCode::INTERNAL_SERVER_ERROR,
                                axum::Json(serde_json::json!({ "error": "qdrant down" })),
                            )
                        }
                    }
                }),
            );
        let (state, cookie, _) = triage_app(upstream).await;

        let uri = format!("/alaya/contradictions/pair?a={a}&b={b}&verdict=supersession&offset=50");
        let (status, html) = get_page(&state, &cookie, &uri).await;
        assert_eq!(status, StatusCode::OK);
        assert!(html.contains(&long), "A's content in full, not clipped");
        assert!(html.contains("short a") && html.contains("tag-a"));
        assert!(
            html.contains(&format!("href=\"/alaya/memory/{}\"", "c".repeat(64))),
            "superseded_by links on"
        );
        assert!(
            html.contains("Could not load this memory: alaya-server 500"),
            "{html}"
        );
        assert!(html.contains("judge-model-x"), "edge verdict fields render");
        assert!(html.contains("Keep B (supersede A)… — recommended"));
        // Every action returns to the page the pair came from.
        assert!(
            html.contains("value=\"/alaya/contradictions?verdict=supersession&amp;offset=50\"")
        );
        assert_eq!(
            seen.lock().unwrap()[0],
            serde_json::json!({ "limit": 50, "offset": 50, "include_resolved": false, "verdicts": ["supersession"] })
        );

        let (status, _) = get_page(
            &state,
            &cookie,
            &format!("/alaya/contradictions/pair?a={a}&b=nope"),
        )
        .await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
    }

    /// AC-5: every decision lands back on the queue view it was taken from,
    /// with a flash naming the pair — and `back` cannot leave the origin.
    #[tokio::test]
    async fn decisions_return_to_the_queue_view_and_never_off_site() {
        let a = "a".repeat(64);
        let b = "b".repeat(64);
        let seen = Seen::default();
        let ok = |_: &serde_json::Value| (StatusCode::OK, serde_json::json!({ "success": true }));
        let upstream = Router::new()
            .route("/contradictions/resolution", recording(&seen, ok))
            .route("/supersede", recording(&seen, ok));
        let (state, cookie, csrf) = triage_app(upstream).await;
        let back = "/alaya/contradictions?verdict=coexist&offset=50";
        let back_enc: String = url::form_urlencoded::byte_serialize(back.as_bytes()).collect();

        let resp = post_form(
            &state,
            &cookie,
            "/alaya/contradictions/keep-both",
            format!("csrf={csrf}&memory_a_hash={a}&memory_b_hash={b}&back={back_enc}"),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        assert_eq!(location(&resp), back);
        let flash = flash_of(&state, &resp);
        assert!(
            flash.msg.contains(&a[..12]) && flash.msg.contains(&b[..12]),
            "{}",
            flash.msg
        );

        let resp = post_form(
            &state,
            &cookie,
            "/alaya/supersede",
            format!("csrf={csrf}&old_hash={a}&new_hash={b}&reason=stale&back={back_enc}"),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        assert_eq!(location(&resp), back);
        assert!(flash_of(&state, &resp).msg.contains(&a[..12]));

        let resp = post_form(
            &state,
            &cookie,
            "/alaya/contradictions/keep-both",
            format!("csrf={csrf}&memory_a_hash={a}&memory_b_hash={b}&back=%2F%2Fevil.test"),
        )
        .await;
        assert_eq!(location(&resp), "/", "safe_next refuses an off-site back");
    }

    /// AC-6: a bad CSRF token writes nothing, however many pairs it carries.
    #[tokio::test]
    async fn bulk_keep_both_with_a_bad_csrf_makes_no_upstream_call() {
        let seen = Seen::default();
        let upstream = Router::new().route(
            "/contradictions/resolution",
            recording(&seen, |_| {
                (StatusCode::OK, serde_json::json!({ "success": true }))
            }),
        );
        let (state, cookie, _) = triage_app(upstream).await;
        let pair = format!("{}:{}", "a".repeat(64), "b".repeat(64));
        let resp = post_form(
            &state,
            &cookie,
            "/alaya/contradictions/keep-both/bulk",
            format!("csrf=WRONG&pair={pair}&pair={pair}"),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
        assert!(seen.lock().unwrap().is_empty());
    }

    /// AC-6: a partial failure names every failed pair and its cause — a
    /// `200 {"success": false}` included — and is flashed as an error.
    #[tokio::test]
    async fn bulk_keep_both_reports_each_failed_pair() {
        let (a, b, c, d) = (
            "a".repeat(64),
            "b".repeat(64),
            "c".repeat(64),
            "d".repeat(64),
        );
        let seen = Seen::default();
        let upstream = Router::new().route(
            "/contradictions/resolution",
            recording(&seen, |body| {
                match body["memory_a_hash"].as_str().unwrap().as_bytes()[0] {
                    b'a' => (StatusCode::OK, serde_json::json!({ "success": true })),
                    b'b' => (
                        StatusCode::NOT_FOUND,
                        serde_json::json!({ "error": "no CONTRADICTS edge" }),
                    ),
                    _ => (
                        StatusCode::OK,
                        serde_json::json!({ "success": false, "error": "graph down" }),
                    ),
                }
            }),
        );
        let (state, cookie, csrf) = triage_app(upstream).await;
        let resp = post_form(
            &state,
            &cookie,
            "/alaya/contradictions/keep-both/bulk",
            format!("csrf={csrf}&pair={a}:{b}&pair={b}:{c}&pair={c}:{d}"),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        assert_eq!(location(&resp), "/alaya/contradictions");
        let flash = flash_of(&state, &resp);
        assert_eq!(flash.kind, "error");
        assert!(
            flash
                .msg
                .starts_with("Kept both for 1 of 3 pairs. 2 not confirmed"),
            "{}",
            flash.msg
        );
        assert!(flash.msg.contains(&format!("{}↔{}", &b[..12], &c[..12])));
        assert!(flash.msg.contains("no CONTRADICTS edge"));
        assert!(flash.msg.contains(&format!(
            "{}↔{} (alaya-server: graph down)",
            &c[..12],
            &d[..12]
        )));

        let bodies = seen.lock().unwrap().clone();
        assert_eq!(bodies.len(), 3, "one call per selected pair");
        for body in &bodies {
            assert_eq!(body["resolution"], "keep_both");
            assert_eq!(body["resolved_via"], "operator:console");
        }
    }

    /// AC-6: a malformed selection or one over the page size writes nothing.
    #[tokio::test]
    async fn bulk_keep_both_refuses_a_bad_selection_before_any_write() {
        let seen = Seen::default();
        let upstream = Router::new().route(
            "/contradictions/resolution",
            recording(&seen, |_| {
                (StatusCode::OK, serde_json::json!({ "success": true }))
            }),
        );
        let (state, cookie, csrf) = triage_app(upstream).await;
        let good = format!("{}:{}", "a".repeat(64), "b".repeat(64));
        for form in [
            format!("csrf={csrf}&pair={good}&pair=nothex:{}", "b".repeat(64)),
            format!("csrf={csrf}{}", format!("&pair={good}").repeat(51)),
            format!("csrf={csrf}"),
        ] {
            let resp = post_form(
                &state,
                &cookie,
                "/alaya/contradictions/keep-both/bulk",
                form,
            )
            .await;
            assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
        }
        assert!(seen.lock().unwrap().is_empty());
    }

    /// AC-7: Reopen clears the stamp with an explicit `resolution: null`,
    /// in both directions (a stamp on either edge settles the pair), behind
    /// the same CSRF check. No reverse edge is the normal case; a real
    /// failure clearing it is reported, never flashed as success.
    #[tokio::test]
    async fn reopen_clears_both_directions_with_a_null_resolution() {
        let (a, b) = ("a".repeat(64), "b".repeat(64));
        let seen = Seen::default();
        let reverse_fails = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
        let flag = reverse_fails.clone();
        let upstream = Router::new().route(
            "/contradictions/resolution",
            recording(&seen, move |body| {
                if body["memory_a_hash"].as_str().unwrap().starts_with('a') {
                    return (StatusCode::OK, serde_json::json!({ "success": true }));
                }
                let error = if flag.load(std::sync::atomic::Ordering::SeqCst) {
                    "Graph operation failed"
                } else {
                    "Resource not found"
                };
                (
                    StatusCode::OK,
                    serde_json::json!({ "success": false, "error": error }),
                )
            }),
        );
        let (state, cookie, csrf) = triage_app(upstream).await;
        let form = |token: &str| {
            format!(
                "csrf={token}&memory_a_hash={a}&memory_b_hash={b}&back=%2Falaya%2Fcontradictions%3Fresolved%3D1"
            )
        };

        let resp = post_form(
            &state,
            &cookie,
            "/alaya/contradictions/reopen",
            form("WRONG"),
        )
        .await;
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
        assert!(seen.lock().unwrap().is_empty());

        let resp = post_form(&state, &cookie, "/alaya/contradictions/reopen", form(&csrf)).await;
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        assert_eq!(location(&resp), "/alaya/contradictions?resolved=1");
        let flash = flash_of(&state, &resp);
        assert_eq!(flash.kind, "ok", "{}", flash.msg);
        assert!(flash.msg.contains("back in the queue"));
        let bodies = seen.lock().unwrap().clone();
        assert_eq!(
            bodies,
            [
                serde_json::json!({
                    "memory_a_hash": a, "memory_b_hash": b,
                    "resolution": null, "resolved_via": "operator:console",
                }),
                serde_json::json!({
                    "memory_a_hash": b, "memory_b_hash": a,
                    "resolution": null, "resolved_via": "operator:console",
                }),
            ]
        );

        reverse_fails.store(true, std::sync::atomic::Ordering::SeqCst);
        let resp = post_form(&state, &cookie, "/alaya/contradictions/reopen", form(&csrf)).await;
        let flash = flash_of(&state, &resp);
        assert_eq!(flash.kind, "error");
        assert!(
            flash.msg.contains("Graph operation failed"),
            "{}",
            flash.msg
        );
        assert!(!flash.msg.contains("back in the queue"));
    }

    /// A gone a→b edge (a stale pair page, or deleted since) must not stop
    /// Reopen clearing a stamp on b→a, which alone keeps the pair hidden.
    /// Only when neither direction was cleared does the request fail.
    #[tokio::test]
    async fn reopen_clears_the_reverse_stamp_when_the_forward_edge_is_gone() {
        let seen = Seen::default();
        // Every a→x edge is gone; x→a is stamped (b), gone (c) or fails (d).
        let upstream = Router::new().route(
            "/contradictions/resolution",
            recording(&seen, |body| {
                let error = match body["memory_a_hash"].as_str().unwrap().as_bytes()[0] {
                    b'b' => return (StatusCode::OK, serde_json::json!({ "success": true })),
                    b'd' => "Graph operation failed",
                    _ => "Resource not found",
                };
                (
                    StatusCode::OK,
                    serde_json::json!({ "success": false, "error": error }),
                )
            }),
        );
        let (state, cookie, csrf) = triage_app(upstream).await;
        let reopen = |other: char| {
            let (a, b) = ("a".repeat(64), other.to_string().repeat(64));
            let form = format!("csrf={csrf}&memory_a_hash={a}&memory_b_hash={b}");
            post_form(&state, &cookie, "/alaya/contradictions/reopen", form)
        };

        let resp = reopen('b').await;
        assert_eq!(resp.status(), StatusCode::SEE_OTHER);
        let flash = flash_of(&state, &resp);
        assert_eq!(flash.kind, "ok", "{}", flash.msg);
        assert!(flash.msg.contains("back in the queue"));
        assert_eq!(seen.lock().unwrap().len(), 2);

        assert_eq!(reopen('c').await.status(), StatusCode::NOT_FOUND);
        assert_eq!(
            reopen('d').await.status(),
            StatusCode::BAD_GATEWAY,
            "nothing was cleared, so nothing is flashed"
        );
    }
}
