//! Build identity — crate version, git SHA, build timestamp.
//!
//! Verifying "is build X live?" used to require cluster access or a chain of
//! inference (merge → CI push → Flux bump → host process table). Agent
//! runtimes deliberately hold no kubeconfig, so the fix is a self-describing
//! service, not wider credentials (#70).
//!
//! Populated at compile time from `ALAYA_GIT_SHA` / `ALAYA_BUILT_AT`, set as
//! Docker build args by CI. Absence is never a startup failure: a bare
//! `cargo build` reports the crate version with a null SHA and timestamp, so
//! local dev, tests and third-party builds behave identically.

/// Crate semver, e.g. `0.1.0`.
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Git SHA this binary was built from, or `None`. CI passes the full 40-hex
/// commit; a build that passes an abbreviation (`benchmarks/README.md`) reports
/// that prefix, so compare with `starts_with`, not equality.
pub fn git_sha() -> Option<&'static str> {
    verified_sha(option_env!("ALAYA_GIT_SHA"))
}

/// RFC3339 build timestamp, or `None`.
pub fn built_at() -> Option<&'static str> {
    build_timestamp(option_env!("ALAYA_BUILT_AT"))
}

/// Version qualified with the build SHA as semver build metadata, e.g.
/// `0.1.0+2f9c…`. Falls back to the bare version when the SHA is unknown.
///
/// The SHA is appended verbatim rather than abbreviated so a consumer can
/// compare a CI build to `git rev-parse HEAD` with no truncation ambiguity.
pub fn version_qualified() -> String {
    qualify(version(), git_sha())
}

fn qualify(version: &str, git_sha: Option<&str>) -> String {
    match git_sha {
        Some(sha) => format!("{version}+{sha}"),
        None => version.to_string(),
    }
}

/// Accept only a hex SHA of plausible length. Rejects the placeholders a build
/// can legitimately supply — `""` from an unset `ARG`, the Dockerfile's
/// `unknown` default, compose's `dev` — so `git_sha` is either verifiable or
/// explicitly absent, never plausible-looking junk. Short SHAs are kept
/// because `benchmarks/README.md` builds with `git rev-parse --short HEAD`
/// expressly to stamp provenance into `/health/detail`.
fn verified_sha(raw: Option<&str>) -> Option<&str> {
    raw.map(str::trim)
        .filter(|s| (7..=40).contains(&s.len()) && s.bytes().all(|b| b.is_ascii_hexdigit()))
}

/// Non-empty is the whole check: the real case is an unset build arg arriving
/// as `""` (`ARG BUILT_AT=`, compose's `${BUILT_AT:-}`), and the value is
/// otherwise generated by our own CI via `date -u`. Trimmed because k8s and
/// build args ship padded scalars. Not a trust boundary — a hand-passed
/// `--build-arg BUILT_AT=yesterday` yields a cosmetically wrong string in an
/// informational field; `git_sha` is the field verification relies on.
fn build_timestamp(raw: Option<&str>) -> Option<&str> {
    raw.map(str::trim).filter(|s| !s.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SHA: &str = "2f9c1a4b6d8e0f2a4c6e8b0d2f4a6c8e0b2d4f6a";

    /// The real no-build-info path: a test binary compiles without
    /// ALAYA_GIT_SHA/ALAYA_BUILT_AT, so absence must read as absence rather
    /// than a `dev`/`unknown` placeholder a consumer could mistake for a SHA.
    #[test]
    fn unstamped_build_reports_absence_not_placeholder() {
        assert!(!version().is_empty());
        assert_eq!(git_sha(), None);
        assert_eq!(built_at(), None);
        assert_eq!(version_qualified(), version());
    }

    #[test]
    fn qualify_appends_sha_as_build_metadata() {
        assert_eq!(qualify("0.1.0", Some(SHA)), format!("0.1.0+{SHA}"));
        assert_eq!(qualify("0.1.0", None), "0.1.0");
    }

    #[test]
    fn verified_sha_accepts_full_and_short_hex() {
        assert_eq!(verified_sha(Some(SHA)), Some(SHA));
        // benchmarks/README.md stamps `git rev-parse --short HEAD`.
        assert_eq!(verified_sha(Some(&SHA[..7])), Some(&SHA[..7]));
        assert_eq!(verified_sha(Some("  2f9c1a4b  ")), Some("2f9c1a4b"));
    }

    #[test]
    fn verified_sha_rejects_placeholders_and_junk() {
        assert_eq!(verified_sha(None), None);
        assert_eq!(verified_sha(Some("")), None);
        // Dockerfile ARG default and docker-compose default.
        assert_eq!(verified_sha(Some("unknown")), None);
        assert_eq!(verified_sha(Some("dev")), None);
        // Too short to identify a commit, and non-hex of a plausible length.
        assert_eq!(verified_sha(Some(&SHA[..6])), None);
        assert_eq!(verified_sha(Some(&"z".repeat(40))), None);
        assert_eq!(verified_sha(Some(&SHA.repeat(2))), None);
    }

    #[test]
    fn build_timestamp_rejects_unset_arg() {
        assert_eq!(
            build_timestamp(Some("2026-08-09T11:22:33Z")),
            Some("2026-08-09T11:22:33Z")
        );
        assert_eq!(
            build_timestamp(Some("  2026-08-09T11:22:33Z\n")),
            Some("2026-08-09T11:22:33Z")
        );
        assert_eq!(build_timestamp(None), None);
        assert_eq!(build_timestamp(Some("")), None);
        assert_eq!(build_timestamp(Some("   ")), None);
    }
}
